# fly.toml file generated for js-storj on 2023-01-11T20:08:05+01:00

app = "js-storj"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
